import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/sections/navigation";
import { CartProvider } from "@/context/CartContext";
import Cart from "@/app/cart/page";
import PayPalProvider from "@/components/PayPalProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <PayPalProvider>

        <CartProvider>
          <Navigation />
          <main className="pt-16">
            {children}
          </main>
          <Cart  />
        </CartProvider>
                </PayPalProvider>

      </body>
    </html>
  );
}
